library(tidyverse)
# https://www.beeradvocate.com/beer/styles/
beer_styles <- list(
  "Bocks"=c(
    "Doppelbock",
    "Eisbock",
    "Maibock",
    "Traditional",
    "Weizenbock",
    "Bock",
    "Bock Beers",
    "Bocks",
    "Bocks/Dopplebocks",
    "Doppelbocks",
    "German Style Doppelbock",
    "German Style Doppelbock or Eisbock",
    "German Style Strong Bock"),
  "Brown Ales"=c(
    "American Brown Ale",
    "English Brown Ale",
    "English Mild",
    "Altbier",
    "German Style Altbier",
    "Belgian Dark",
    "Brown Ale",
    "American Brown Ales",
    "American Style Brown Ale",
    "Mild Ale - English Dark",
    "Brown Ales",
    "English Style Brown Ale",
    "German Style Brown / Dusseldorf Style Altbier",
    "German Style Brown Ale / Dusseldorf Style Altbier"),
  "Dark Ales"=c(
    "Dubbel",
    "Rye Beer Roggenbier",
    "Roggenbier",
    "Scottish Ale",
    "Scottish Ales",
    "Winter Warmer",
    "Scottish Style Ale",
    "English Dark Mild Ale",
    "English Style Mild Ale",
    "Belgian Dark Ale",
    "Belgian Strong Dark Ale",
    "Belgian Style Abbey Ale",
    "Belgian Style Ale",
    "Belgian Style Ales",
    "Belgian Style Dubbel or Quadrupel"),
  "Dark Lagers"=c(
    "American Amber / Red Lager",
    "American Amber / Red",
    "American Amber",
    "American Red",
    "European Dark",
    "Marzen",
    "German Style Maerzen",
    "German Style Maerzen / Oktoberfest",
    "Märzen / Oktoberfest",
    "Oktoberfest",
    "Munich Dunkel",
    "European Style Dark / Munchner",
    "European Style Dark / Munchner Dunkel",
    "European Style Dark / Munchener Dunkel",
    "European Style Dunkel",
    "Rauchbier",
    "Schwarzbier",
    "German Style Schwarzbier",
    "Vienna",
    "Vienna Lager",
    "Vienna Style Lager",
    "Amber/Viennas",
    "Vienna/Marzen/Octoberfest Beer",
    "American Dark Lager",
    "Amber Lager",
    "American Style Amber Lager",
    'American Style "Light" Amber Lager',
    "American Amber Lager",
    "American Style Dark Lager",
    "Dark Lager",
    "Euro Dark Lager"),
  "Hybrid Beers"=c(
    "Bière de Champagne",
    "Bière Brut",
    "Braggot",
    "California Common",
    "Steam Beer",
    "Cream Ale",
    "American Style Cream Ale",
    "American Style Cream Ale or Lager",
    "American Cream Ales",
    "California Common / Steam Beer",
    "Cream Ales"),
  "India Pale Ales"=c(
    "India Pale Ale",
    "IPA",
    "Double India Pale Ale",
    "Double IPA",
    "American India Pale Ale",
    "American IPA",
    "Belgian India Pale Ale",
    "Belgian IPA",
    "Black India Pales Ale",
    "American Style India Black Ale",
    "Black IPA",
    "Cascadian Dark Ale",
    "Brut India Pales Ale",
    "Brut IPA",
    "English India Pales Ale",
    "English IPA",
    "Imperial India Pales Ale",
    "Imperial IPA",
    "American Double / Imperial IPA",
    "American Double / Imperial Pilsner",
    "New England India Pales Ale",
    "New England IPA",
    "Imperial or Double India Pale Ale",
    "Imperial India Pale Ale",
    "American Black Ale",
    "American Style Black Ale",
    "American White IPA",
    "English India Pale Ale (IPA)",
    "English Style India Pale Ale",
    "American Style India Pale Ale"),
  "Pale Ales"=c(
    "Ales",
    "Belgian  and French Ale",
    "Belgian  and French Style Ale",
    "Belgian and French Style Ale",
    "Bitter",
    "English Style Strong Bitter",
    "Wood  and Barrel aged Strong Beer",
    "English Style (Extra Special) Strong Bitter",
    "(Extra Special) Strong Bitter",
    "English Style Bitter",
    "Ordinary or Special Bitter",
    "English Bitter",
    "Extra Special / Strong Bitter (ESB)",
    "Extra Special",
    "Extra Strong Bitter",
    "Extra Strong Bitter (ESB)",
    "Bitter or Pale Mild Ale",
    "Extra Special Bitter",
    "Extra Special Bitter or Strong Bitter",
    "ESB",
    "Blonde Ale",
    "Belgian Style Blonde Ale or Pale Ale",
    "Other Belgian Style Ale",
    "Blonde/Golden Ales",
    "Golden Ale / Canadian Style Ale",
    "Golden or Blonde Ale",
    "Blond/Golden Ales",
    "Belgian Blonde Ale",
    "American Blonde Ale",
    "Bière de Garde",
    "Saison / Farmhouse Ale",
    "Saison",
    "Farmhouse Ale",
    "Kölsch",
    "German Style Koelsch",
    "German Style Kolsch / Koln Style Kolsch",
    "Pale Ales",
    "English Style Summer Ale",
    "English Mild Pale Ale (EMPA)",
    "English Mild Pale Ale",
    "English Mild",
    "American Pale Ale",
    "American Pale Ale (APA)",
    "APA",
    "Belgain Pale Ale",
    "Belgain Pale Ale (BPA)",
    "English Pale Ale",
    "Classic English Pale Ale",
    "Classic English Style Pale Ale",
    "English Pale Ale (EPA)",
    "Pale Ale",
    "Belgian Pale Ale",
    "American Amber / Red Ale",
    "American Style Amber / Red Ale",
    "American Amber Ale",
    "American Style Amber Ale",
    "American Red Ale",
    "Irish Red Ale",
    "Amber Ale",
    "Amber Ale/American Pale Ales",
    "American Amber/Red Ale",
    "American Style Amber/Red Ale",
    "Amber Ales",
    "American Belgo Style Ale",
    "Alts"),
  "Pale Lagers"=c(
    "American Lagers",
    "American Style Lager",
    "American Style Lager / Ale Or Cream Ale",
    "American Style Lager or American Style Malt Liquor",
    "American Style Lager or American Style Pilsener",
    "American Style Lager or Ice Lager or Malt Liquor",
    "American Style Lager or Light Lager",
    "American Light Lager",
    "American Light Lagers",
    "American Light Pilsners",
    "American Pilsener",
    "American Malt Liquor",
    "American Style Lager or Premium Lager",
    "American Style Lager, Light Lager or Premium Lager",
    "American Style Lager/Ale or Cream",
    "America Style Light Lager",
    "American Style Lager/Ale or Cream Ale",
    "American Style Light Lager",
    "American Style Light Lager or German Style Light Lager",
    "American Pale Lager",
    "American Adjunct Lager",
    "International Style Pilsener",
    "Adjunct Lager",
    "American Lager",
    "European Lager",
    "Munich Helles",
    "Dortmunder Export",
    "Dortmunder or German Style Oktoberfest",
    "Dortmunder / European Style Export",
    "Dortmunder / Export Lager",
    "Dortmunder",
    "European Pale Lager",
    "European Strong Lager",
    "Helles",
    "Helles Lager",
    "Munich Helles Lager",
    "Munchner Style Helles",
    "Munchner Helles",
    "Munchener Helles",
    "Munchener Helles And Export",
    "Munich Style Helles",
    "American India Pale Lager",
    "India Pale Lager (IPL)",
    "India Pale Lager",
    "IPL",
    "Zwickelbier",
    "Kellerbier or Zwickelbier",
    "Kellerbier",
    "Light Lager",
    "Malt Liquor Lager",
    "Malt Liquor",
    "Pilsner",
    "German Style Pilsener",
    "European Pilsner",
    "American Specialty Lager",
    "American Style Specialty Lager",
    "American Style Specialty Lager or Cream Ale or Lager",
    "American Pilsner",
    "American Pilseners",
    "American Style or International Style Pilsener",
    "European Style Pilsener",
    "American Premium Lager",
    "Bohemian / Czech Pislner",
    "Czech Pilsener",
    "Bohemian Style Pilsener",
    "German Pilsener",
    "Bohemian Pislner",
    "Czech Pislner",
    "German Pislner",
    "Specialty Saison",
    "French  Belgian Style Saison",
    "Classic Saison",
    "French  and Belgian Style Saison",
    "Imperial Pislner",
    "Irish Style Red Ale",
    "Double Hoppy Red Ale",
    "Double Red Ale",
    "International Style Pale Ale",
    "Imperial or Double Red Ale",
    "American Dry Lager",
    "Dry Beers",
    "American Style Pale Ale",
    "American Style Premium Lager"),
  "Porters"=c(
    "Porter",
    "American Porter",
    "Baltic Porter",
    "English Porter",
    "Imperial Porter",
    "Robust Porter",
    "Smoked Porter",
    "Robust Porter",
    "Porters",
    "Baltic Style Porter",
    "Brown Porter"),
  "Specialty Beers"=c(
    "Chili Beer",
    "Chile Beer",
    "Sahti",
    "Coffee Beer",
    "Coffee Flavored Beer",
    "Fruit and Field Beer",
    "Belgian Style Fruit Beer",
    "American Style Fruit Beer",
    "Gruit / Ancient Herbed Ale",
    "Happoshu",
    "Herb and Spice Beer",
    "Kvass",
    "Japanese Rice",
    "Low Alcohol Beer",
    "Pumpkin Beer",
    "Rye Beer",
    "Specialty Honey Lagers or Ales",
    "Specialty Honey Beer",
    "Specialty Honey Ales Or Lagers",
    "Smoke Flavored",
    "Smoke Beer",
    "Smoke Flavored Beer",
    "Smoked Beer",
    "Smoke Flavored Beers",
    "Specialty Beer",
    "Belgian Style Specialty Ale",
    "Belgian Style Strong Specialty Ale",
    "Pumpkin/Squash Beer or Pumpkin Spice Beer",
    "Session Beer",
    "Session India Pale Ale",
    "Pumpkin Ale",
    "Proam",
    "Pro Am Competition",
    "Non Alcoholic Malt Beverage",
    "Non Alcoholic (Beer) Malt Beverage",
    "Honey Beer",
    "Chocolate / Cocoa Flavored Beer",
    "Chocolate Beer",
    "Experimental Beer",
    "Experimental Beer (Lager or Ale)",
    "Gluten Free Beer",
    "Aged Beer",
    "Aged Beer (Ale or Lager)",
    "Wood  and Barrel aged Beer",
    "Specialty Honey Lager or Ale",
    "Specialty"),
  "Stouts"=c(
    "Stout",
    "Stouts",
    "Milk / Sweet Stout",
    "Sweet Stout",
    "American Stout",
    "American Imperial Stout",
    "English Stout",
    "Foreign Stout",
    "Foreign / Export Stout",
    "Export Stout",
    "Irish Dry Stout",
    "Oatmeal Stout",
    "Russian Imperial Stout",
    "Imperial Stout",
    "Sweet / Milk Stout",
    "Classic Irish Dry Stout",
    "Sweet Stout or Cream Stout",
    "Wood  and Barrel Aged Strong Stout",
    "American Style Stout",
    "American Double / Imperial Stout",
    "British Stout",
    "Classic Irish Style Dry Stout",
    "Coffee Stout or Porter",
    "Dry Stout",
    "Dry Stouts",
    "Foreign (Export) Style Stout",
    "Foreign Style Stout",
    "Specialty Stouts"),
  "Strong Ales"=c(
    "Barley wine",
    "Barley Wine Style Ale",
    "American Barleywine",
    "American Barley wine",
    "English Barley wine",
    "Old Ale",
    "Scotch Ale",
    "Quadrupel (Quad)",
    "Imperial Red Ale",
    "Scotch Ale / Wee Heavy",
    "Strong Ale",
    "Strong Ales",
    "American Strong Pale Ale",
    "American Style Strong Pale Ale",
    "American Strong Ale",
    "Belgian Dark Strong Ale",
    "Belgian Pale Strong Ale",
    "English Strong Ale",
    "Barley Wine Ale",
    "Barley Wine",
    "Barley Wines",
    "Belgian Strong Pale Ale",
    "Tripel",
    "Belgian Style Tripel",
    "Strong Scotch Ale",
    "Other Strong Beer",
    "Other Strong Ale or Lager",
    "Wheatwine Wheat Beer",
    "Old Ale/Strong Ale",
    "Old Ale or Strong Ale"),
  "Wheat Beers"=c(
    "American Dark Wheat Beer",
    "American Pale Wheat Beer",
    "Dunkelweizen",
    "Hefeweizen",
    "American Hefeweizen",
    "American Style Hefeweizen",
    "Kristallweizen",
    "Witbier",
    "Belgian Style Witbier",
    "American Pale Wheat Ale",
    "German Style Wheat Ale",
    "American Wheat Ale or Lager",
    "American Wheat Beer",
    "American Wheat Beer with Yeast",
    "South German Style Hefeweizen",
    "South German Style Hefeweizen/Hefeweissbier",
    "Berliner Weissbier",
    "American Style Wheat Ale or Lager",
    "American Style Wheat Beer",
    "American Style Wheat Beer with Yeast",
    "American Wheat Ale Or Lager",
    "American Wheats",
    "American Style Wheat Beer With Yeast",
    "Wheat Beers"),
  "Wild/Sour Beers"=c(
    "Fruit / Vegetable Beer",
    "Fruit And Vegetable Beer",
    "Fruit Beer",
    "Fruit Wheat Beer",
    "Fruit, Vegetable",
    "Fruited American Style Sour Ale",
    "German Style Sour Ale",
    "Fruited Wood  and Barrel Aged Sour Beer",
    "Brett Beer",
    "American Style Brett Ale",
    "American Style Brett Beer",
    "Faro",
    "Fruit",
    "Gueuze",
    "Traditional",
    "Berliner Weisse",
    "Flanders Oud Bruin",
    "Flanders Red Ale",
    "Gose",
    "Wild Ale",
    "American Fruit Beer",
    "Raspberry Beers",
    "American Style Sour Ale",
    "Belgian Style Lambic or Sour Ale",
    "Belgian Style Sour Ale",
    "Cider",
    "Field Beer",
    "Field Beer or Pumpkin Beer",
    "Wood  and Barrel Aged Sour Beer")
)
beer_styles <- lapply(names(beer_styles), function(beer)
  data.frame(category=beer_styles[[beer]], style=beer)) %>%
  bind_rows()
write_csv(beer_styles,
          "content/post/2020-10-20-great-american-beer-festival/beer_styles.csv")